### ISSUE TITLE
Plotly Graphs are not showing on HTML

### ISSUE THREAD

**Issue by RanFeldesh** [Conestoga-AAIML-2023-Spring/CSCN8010-lab-submissions#42]
Plotly might not show the graphs on the HTML, while showing them on the notebook. 
This is a common issue. 

#### Solution
The solution is a one-line added at the top of the notebook, after  the imports:

```python
plotly.offline.init_notebook_mode()

```
(reference: https://stackoverflow.com/a/58718006/) 

#### Example
See cell number 2 here:
https://github.com/Conestoga-AAIML-2023-Spring/CSCN8010/blob/main/class_notebooks/github_pages/index.ipynb

**Comment by Dwarakanath216** [comment]
Thank you, Professor. It works after adding the one-line code as mentioned in the above issue. I am attaching the before and after screenshots for the reference of my peers.
![Before](https://github.com/Conestoga-AAIML-2023-Spring/CSCN8010-lab-submissions/assets/100982839/ef1bdb6c-7a17-4d05-83ff-cf0b48367e1b)
![image](https://github.com/Conestoga-AAIML-2023-Spring/CSCN8010-lab-submissions/assets/100982839/09dd08ac-4b89-4e03-8a76-c58268dbb289)
